// <auto-generated />
namespace com.BookSpider.DomainService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_updatetimes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_updatetimes));
        
        string IMigrationMetadata.Id
        {
            get { return "201801151428117_Add_updatetimes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
