// <auto-generated />
namespace com.miaow.DomainService.NovelDomainServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_lastupdatetime_for_novel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_lastupdatetime_for_novel));
        
        string IMigrationMetadata.Id
        {
            get { return "201802101413135_add_lastupdatetime_for_novel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
