// <auto-generated />
namespace com.miaow.DomainService.NovelDomainServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_fields_sortId_chapterCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_fields_sortId_chapterCount));
        
        string IMigrationMetadata.Id
        {
            get { return "201802091741327_add_fields_sortId_chapterCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
